#!/bin/bash

DEFAULT_HOST=0.0.0.0
DEFAULT_PORT=1234

HOST=${REVCONN_HOST:-$DEFAULT_HOST}
PORT=${REVCONN_PORT:-$DEFAULT_PORT}

while true; do
    socat -d -d - "tcp-l:${PORT},bind=${HOST},reuseaddr" || exit
    echo '--------------------------------------------------'
done
