#!/usr/bin/env python3
import os
import subprocess
import sys

DEFAULT_HOST = 'localhost'
DEFAULT_PORT = 13337

# The command is firstly parsed by socat, then by shell.
# Socat parsing seems buggy. `revterm_client echo 1\'2` causes "E internal: miscalculated string lengths".


def socat_repr(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


if __name__ == '__main__':
    command = sys.argv[1] if len(sys.argv) > 1 else 'bash -il'
    host = os.getenv('REVTERM_HOST') or DEFAULT_HOST
    port = os.getenv('REVTERM_PORT') or str(DEFAULT_PORT)
    sys.exit(subprocess.call(['socat',
                              'exec:%s,pty,stderr,setsid,sigint,sane' % socat_repr(command),
                              'tcp:%s:%s' % (host, port)]))
